SELECT
TO_CHAR(TRANDATE, 'MON-DD-YYYY HH24:MI:SS') AS "Transaction DateTime" ,
"PATRONINFO"."LASTNAME", 
"PATRONINFO"."FIRSTNAME", 
TO_CHAR(KEYVALUE) AS "PIK ID" ,
"ACTIVITYTRANLEDGER"."LOCATION",
"LOCATIONDESCRIPTION"."LONGDES", 
"ACTIVITYTRANLEDGER"."REASONMSG"

 
 FROM   (("DIEBOLD"."ACTIVITYTRANLEDGER_VR" "ACTIVITYTRANLEDGER" 
 
 LEFT OUTER JOIN "DIEBOLD"."LOCATIONDESCRIPTION_VR" "LOCATIONDESCRIPTION" 
 ON "ACTIVITYTRANLEDGER"."LOCATION"="LOCATIONDESCRIPTION"."LOCATION") 
 
 LEFT OUTER JOIN "DIEBOLD"."KEYMAPPINGINFO" "KEYMAPPINGINFO" 
 ON "ACTIVITYTRANLEDGER"."PATRONID"="KEYMAPPINGINFO"."PATRONID") 
 
 LEFT OUTER JOIN "DIEBOLD"."PATRONINFO" "PATRONINFO" 
 ON "ACTIVITYTRANLEDGER"."PATRONID"="PATRONINFO"."PATRONID"
 
 
WHERE  "ACTIVITYTRANLEDGER"."ACCOUNTTYPE"=5 AND ("KEYMAPPINGINFO"."MEDIATYPE" IS  NULL  OR "KEYMAPPINGINFO"."MEDIATYPE"='-1') 
 
 AND "ACTIVITYTRANLEDGER"."REASONMSG" = 'Approved'
 
 AND ("ACTIVITYTRANLEDGER"."TRANDATE" >= TO_DATE ('14-10-2019 07:00:00', 'DD-MM-YYYY HH24:MI:SS') 
 
 AND "ACTIVITYTRANLEDGER"."TRANDATE" < TO_DATE ('18-10-2019 09:30:00', 'DD-MM-YYYY HH24:MI:SS')) 
 
 AND "ACTIVITYTRANLEDGER"."LOCATION"=38312
 
Order by TRANDATE ASC
 ;