
/*Oracle DB CS_GOLD Script created by Mike Cvetanovich */ 

SELECT 
MAX(TO_CHAR(TRANDATE, 'MON-DD-YYYY')) AS "Transaction DATE" ,
TO_CHAR(TRANDATE, 'HH24:MI:SS') AS "Transaction TIME" ,
"PATRONINFO"."LASTNAME", 
"PATRONINFO"."FIRSTNAME", 
TO_CHAR(KEYVALUE) AS "PIK ID" ,
--"KEYMAPPINGINFO"."KEYVALUE", 
"ACTIVITYTRANLEDGER"."LOCATION",
"LOCATIONDESCRIPTION"."LONGDES", 
"ACTIVITYTRANLEDGER"."REASONMSG"


 FROM   (("DIEBOLD"."ACTIVITYTRANLEDGER_VR" "ACTIVITYTRANLEDGER" 

 LEFT OUTER JOIN "DIEBOLD"."LOCATIONDESCRIPTION_VR" "LOCATIONDESCRIPTION" 
 ON "ACTIVITYTRANLEDGER"."LOCATION"="LOCATIONDESCRIPTION"."LOCATION") 

 LEFT OUTER JOIN "DIEBOLD"."KEYMAPPINGINFO" "KEYMAPPINGINFO" 
 ON "ACTIVITYTRANLEDGER"."PATRONID"="KEYMAPPINGINFO"."PATRONID") 

 LEFT OUTER JOIN "DIEBOLD"."PATRONINFO" "PATRONINFO" 
 ON "ACTIVITYTRANLEDGER"."PATRONID"="PATRONINFO"."PATRONID"

WHERE  "ACTIVITYTRANLEDGER"."ACCOUNTTYPE"=5 AND ("KEYMAPPINGINFO"."MEDIATYPE" IS  NULL  OR "KEYMAPPINGINFO"."MEDIATYPE"='-1') 
AND "ACTIVITYTRANLEDGER"."REASONMSG" = 'Approved'

/*  ---RUN THIS TO SET MANUAL DATE_TIME OR TRIGGER ON FRIDAY AFTER 9 AM
AND (
"ACTIVITYTRANLEDGER"."TRANDATE" >= TO_DATE('16-12-2018', 'DD-MM-YYYY') + 1/24/60/60
AND "ACTIVITYTRANLEDGER"."TRANDATE" < TO_DATE ('13-12-2018', 'DD-MM-YYYY') 
AND "ACTIVITYTRANLEDGER"."TRANDATE" >= TO_DATE('07:00:00', 'HH24:MI:SS')
AND "ACTIVITYTRANLEDGER"."TRANDATE" <= TO_DATE('10:00:00', 'HH24:MI:SS')
)
*/

AND "ACTIVITYTRANLEDGER"."TRANDATE" >= trunc(sysdate)-5   -- HERE THE "-5" PRODUCES A TRUNCATED SYSDATE STARTING BACK 5 DAYS FROM CURRENT DATE
And to_number(to_char("ACTIVITYTRANLEDGER"."TRANDATE", 'HH24')) between 7 and 9   -- CHG "TO_CHAR" TO "TO_NUMBER" SETS TIME TO THE 24 HOUR CLOCK, SET TIME BETWEEN 7a TO 9a

AND "ACTIVITYTRANLEDGER"."LOCATION"=38312   -- *** SET LOCATION HERE  ***

group by TO_CHAR(TRANDATE, 'HH24:MI:SS'), "PATRONINFO"."LASTNAME", "PATRONINFO"."FIRSTNAME", TO_CHAR(KEYVALUE), "ACTIVITYTRANLEDGER"."LOCATION", 
"LOCATIONDESCRIPTION"."LONGDES", "ACTIVITYTRANLEDGER"."REASONMSG"

ORDER BY 1 ASC, 2 ASC